cache:
  7edae503881d4819:
    intent: ratchet_intent_classify
    domain: system
    zone: green
    handler: ratchet_interpreter
    handler_args:
      classifier: intent
      prompt_template: classify_intent
    intent_type: actionable
    confirmed_count: 1
    last_confirmed: '2026-03-19T19:11:52.182249+00:00'
    original_input: some random input
    confidence: 1.0
  a3d9c6b42712058d:
    intent: ratchet_intent_classify
    domain: system
    zone: green
    handler: ratchet_interpreter
    handler_args:
      classifier: intent
      prompt_template: classify_intent
    intent_type: actionable
    confirmed_count: 1
    last_confirmed: '2026-03-19T19:11:57.197144+00:00'
    original_input: unknown command
    confidence: 1.0
